---
- name: Cenots7 deployment playbook
  hosts: all      # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: root         # Update username for remote server
  vars:
    tomcat_version: 8.5.23
    tomcat_permissions_production: True
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui,manager-script,admin-gui"
      - username: "exampleuser"
        password: "us3rp@ssw0rd"
        roles: "tomcat"         
    java_packages:
      - java-1.8.0-openjdk
  roles:
    # - zaxos.tomcat-ansible-role
    # - geerlingguy.java
    # - jenkins
    # - grafana
    # - prometheus
    # - tomcat
    # - mariadb
    # - { role: tecris.maven, maven_major: 3, maven_version: 3.8.6, maven_home_parent_directory: /opt }